layout_spectrum: 0
favicon: null
name: S Morgan Creative
purpose: []
analytics:
  facebook: null
  google: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  version: null
  bucket: null
color:
  brandStrength: 1
  lightness: 0.4627299061976373
  saturation: 0.5429354831576347
  rhythmicContrast: 0.960515518905595
  brandColors:
    - '#FBEAD0'
    - '#15205B'
    - '#C6B4A3'
    - '#6E6E77'
    - '#FCB666'
typography_spectrum: 0.7893617
