name: S Morgan Creative
favicon: null
layout_spectrum: 0.28565799607895315
typography_spectrum: 0.7375189487356693
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.751734952442348
  lightness: 0.4627299061976373
  saturation: 0.5429354831576347
  rhythmicContrast: 0.960515518905595
purpose: []
